# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\frameSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 338)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameSettings = QtWidgets.QFrame(Form)
        self.frameSettings.setEnabled(True)
        self.frameSettings.setObjectName("frameSettings")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameSettings)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea = QtWidgets.QScrollArea(self.frameSettings)
        self.scrollArea.setStyleSheet("QScrollArea {  \n"
"    border: 3px solid rgba(255, 219, 41, 255);;  \n"
"    border-radius: 15px;  \n"
"    padding: 5px 5px 5px 3px; \n"
"}  \n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 351, 616))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frameVolume = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frameVolume.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frameVolume.setStyleSheet("QFrame {\n"
"    background-color: none;\n"
"}\n"
"\n"
"#frameVolume{\n"
"    border-radius: 10px;  \n"
"    background-color: rgba(255,255,255, 50);\n"
"    padding: 5px 5px 5px 5px; \n"
"}\n"
"\n"
"QSlider{\n"
"    background-color: none;\n"
"}")
        self.frameVolume.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameVolume.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVolume.setObjectName("frameVolume")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frameVolume)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_3 = QtWidgets.QFrame(self.frameVolume)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.volLabel = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.volLabel.setFont(font)
        self.volLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.volLabel.setObjectName("volLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.volLabel)
        self.verticalLayout_9.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frameVolume)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minVolLabel = QtWidgets.QLabel(self.frame_4)
        self.minVolLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.minVolLabel.setObjectName("minVolLabel")
        self.horizontalLayout_2.addWidget(self.minVolLabel)
        self.volSlider = QtWidgets.QSlider(self.frame_4)
        self.volSlider.setMaximum(350)
        self.volSlider.setProperty("value", 100)
        self.volSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volSlider.setObjectName("volSlider")
        self.horizontalLayout_2.addWidget(self.volSlider)
        self.maxVolLabel = QtWidgets.QLabel(self.frame_4)
        self.maxVolLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxVolLabel.setObjectName("maxVolLabel")
        self.horizontalLayout_2.addWidget(self.maxVolLabel)
        self.verticalLayout_9.addWidget(self.frame_4)
        self.verticalLayout_6.addWidget(self.frameVolume)
        self.frameVoiceSpeed = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frameVoiceSpeed.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frameVoiceSpeed.setStyleSheet("QFrame {\n"
"    background-color: none;\n"
"}\n"
"\n"
"#frameVoiceSpeed{\n"
"    border-radius: 10px;  \n"
"    background-color: rgba(255,255,255, 50);\n"
"    padding: 2px 5px 2px 5px;\n"
"}\n"
"\n"
"QDoubleSpinBox{\n"
"    border-radius: 3px;  \n"
"    background-color: rgba(255,255,255, 50);\n"
"}")
        self.frameVoiceSpeed.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameVoiceSpeed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVoiceSpeed.setObjectName("frameVoiceSpeed")
        self.gridLayout = QtWidgets.QGridLayout(self.frameVoiceSpeed)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.frameVoiceSpeed)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(170, 16777215))
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.speachSpeedSpinBox = QtWidgets.QDoubleSpinBox(self.frameVoiceSpeed)
        self.speachSpeedSpinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.speachSpeedSpinBox.setMinimum(0.25)
        self.speachSpeedSpinBox.setMaximum(2.5)
        self.speachSpeedSpinBox.setSingleStep(0.25)
        self.speachSpeedSpinBox.setProperty("value", 1.0)
        self.speachSpeedSpinBox.setObjectName("speachSpeedSpinBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.speachSpeedSpinBox)
        self.gridLayout.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frameVoiceSpeed)
        self.switchDialCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.switchDialCheckBox.setEnabled(False)
        self.switchDialCheckBox.setStyleSheet("QCheckBox {\n"
"    border-radius: 10px;  \n"
"    background-color: rgba(255,255,255, 50);\n"
"    padding-left: 3px;\n"
"    padding: 2px 5px 2px 5px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    background-color: rgba(255,255,255, 20);\n"
"    color:  rgba(255,255,255, 180);\n"
"}\n"
"")
        self.switchDialCheckBox.setObjectName("switchDialCheckBox")
        self.verticalLayout_6.addWidget(self.switchDialCheckBox)
        self.framePlayerNicks = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.framePlayerNicks.setStyleSheet("QFrame {\n"
"    background-color: none;\n"
"}\n"
"\n"
"#framePlayerNicks{\n"
"    border: 3px solid rgba(255,50,50, 0);\n"
"    border-radius: 10px;  \n"
"    background-color: rgba(255,255,255, 50);\n"
"}\n"
"\n"
"#groupBoxPlayerNicks, #groupBoxTrevelerGender{\n"
"    border-radius: 10px;  \n"
"    background-color: rgba(255,255,255, 0);\n"
"}\n"
"\n"
"QRadioButton {\n"
"    background-color: rgba(255,255,255, 0);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 1px solid rgba(255,255,255, 40);\n"
"    border-radius: 8px;  \n"
"    background-color: rgba(255,255,255, 40);\n"
"    padding-left: 5px;\n"
"}\n"
"QLineEdit::hover{\n"
"    border-color:  rgba(255,255,255, 150);\n"
"}\n"
"QLineEdit:disabled, QLabel:disabled, QGroupBox:disabled, QRadioButton:disabled{\n"
"    color:  rgba(255,255,255, 180);\n"
"}")
        self.framePlayerNicks.setObjectName("framePlayerNicks")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.framePlayerNicks)
        self.verticalLayout_8.setContentsMargins(-1, 5, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBoxPlayerNicks = QtWidgets.QGroupBox(self.framePlayerNicks)
        self.groupBoxPlayerNicks.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxPlayerNicks.setFlat(True)
        self.groupBoxPlayerNicks.setCheckable(True)
        self.groupBoxPlayerNicks.setObjectName("groupBoxPlayerNicks")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxPlayerNicks)
        self.verticalLayout_2.setContentsMargins(-1, 18, -1, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBoxPlayerNicks)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.PlayerNameLineEdit = QtWidgets.QLineEdit(self.groupBoxPlayerNicks)
        self.PlayerNameLineEdit.setObjectName("PlayerNameLineEdit")
        self.verticalLayout_2.addWidget(self.PlayerNameLineEdit)
        self.label_6 = QtWidgets.QLabel(self.groupBoxPlayerNicks)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.VoicePlayerNameLineEdit = QtWidgets.QLineEdit(self.groupBoxPlayerNicks)
        self.VoicePlayerNameLineEdit.setInputMask("")
        self.VoicePlayerNameLineEdit.setText("")
        self.VoicePlayerNameLineEdit.setObjectName("VoicePlayerNameLineEdit")
        self.verticalLayout_2.addWidget(self.VoicePlayerNameLineEdit)
        self.groupBoxTrevelerGender = QtWidgets.QGroupBox(self.groupBoxPlayerNicks)
        self.groupBoxTrevelerGender.setEnabled(True)
        self.groupBoxTrevelerGender.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBoxTrevelerGender.setFlat(True)
        self.groupBoxTrevelerGender.setObjectName("groupBoxTrevelerGender")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBoxTrevelerGender)
        self.horizontalLayout_3.setContentsMargins(-1, 18, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.maleTrevelerGb = QtWidgets.QRadioButton(self.groupBoxTrevelerGender)
        self.maleTrevelerGb.setChecked(True)
        self.maleTrevelerGb.setObjectName("maleTrevelerGb")
        self.horizontalLayout_3.addWidget(self.maleTrevelerGb)
        self.femaleTrevelerGb = QtWidgets.QRadioButton(self.groupBoxTrevelerGender)
        self.femaleTrevelerGb.setObjectName("femaleTrevelerGb")
        self.horizontalLayout_3.addWidget(self.femaleTrevelerGb)
        self.verticalLayout_2.addWidget(self.groupBoxTrevelerGender)
        self.verticalLayout_8.addWidget(self.groupBoxPlayerNicks)
        self.nickQuestionBtn = QtWidgets.QPushButton(self.framePlayerNicks)
        self.nickQuestionBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.nickQuestionBtn.setObjectName("nickQuestionBtn")
        self.verticalLayout_8.addWidget(self.nickQuestionBtn)
        self.verticalLayout_6.addWidget(self.framePlayerNicks)
        self.muteNoEventNpcCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.muteNoEventNpcCheckBox.setMinimumSize(QtCore.QSize(0, 37))
        self.muteNoEventNpcCheckBox.setStyleSheet("QCheckBox {\n"
"    border-radius: 10px;  \n"
"    background-color: rgba(255,255,255, 50);\n"
"    padding-left: 3px;\n"
"    padding: 2px 5px 2px 5px;\n"
"    height:20;\n"
"}\n"
"")
        self.muteNoEventNpcCheckBox.setChecked(True)
        self.muteNoEventNpcCheckBox.setTristate(False)
        self.muteNoEventNpcCheckBox.setObjectName("muteNoEventNpcCheckBox")
        self.verticalLayout_6.addWidget(self.muteNoEventNpcCheckBox)
        self.groupBoxProcessers = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxProcessers.setStyleSheet("QFrame {\n"
"    background-color: none;\n"
"}\n"
"\n"
"#groupBoxProcessers{\n"
"    border-radius: 10px;  \n"
"    background-color: rgba(255,255,255, 50);\n"
"}\n"
"QRadioButton{\n"
"    background-color: none;\n"
"}\n"
"")
        self.groupBoxProcessers.setObjectName("groupBoxProcessers")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxProcessers)
        self.gridLayout_2.setContentsMargins(-1, 18, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.CPU_rBtn = QtWidgets.QRadioButton(self.groupBoxProcessers)
        self.CPU_rBtn.setObjectName("CPU_rBtn")
        self.verticalLayout_7.addWidget(self.CPU_rBtn)
        self.GPU_rBtn = QtWidgets.QRadioButton(self.groupBoxProcessers)
        self.GPU_rBtn.setObjectName("GPU_rBtn")
        self.verticalLayout_7.addWidget(self.GPU_rBtn)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.label_2 = QtWidgets.QLabel(self.groupBoxProcessers)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 85, 0)")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBoxProcessers)
        self.groupBoxMonitors = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxMonitors.setStyleSheet("QFrame {\n"
"    background-color: none;\n"
"}\n"
"\n"
"#groupBoxMonitors{\n"
"    border-radius: 10px;  \n"
"    background-color: rgba(255,255,255, 50);\n"
"    padding-top: 8px;\n"
"}\n"
"")
        self.groupBoxMonitors.setObjectName("groupBoxMonitors")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxMonitors)
        self.gridLayout_3.setContentsMargins(-1, 12, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.choiceMonitorCB = QtWidgets.QComboBox(self.groupBoxMonitors)
        self.choiceMonitorCB.setStyleSheet("border-radius: 8px;  \n"
"background-color: rgba(255,255,255, 50);\n"
"padding-left:5px;")
        self.choiceMonitorCB.setObjectName("choiceMonitorCB")
        self.gridLayout_3.addWidget(self.choiceMonitorCB, 0, 0, 1, 1)
        self.showMonitorNumbers = QtWidgets.QPushButton(self.groupBoxMonitors)
        self.showMonitorNumbers.setObjectName("showMonitorNumbers")
        self.gridLayout_3.addWidget(self.showMonitorNumbers, 1, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBoxMonitors)
        self.showCV_chBtn = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.showCV_chBtn.setMinimumSize(QtCore.QSize(0, 37))
        self.showCV_chBtn.setStyleSheet("QCheckBox {\n"
"    border-radius: 10px;  \n"
"    background-color: rgba(255,255,255, 50);\n"
"    padding-left: 3px;\n"
"    padding: 2px 5px 2px 5px;\n"
"    height:20;\n"
"}\n"
"")
        self.showCV_chBtn.setChecked(False)
        self.showCV_chBtn.setObjectName("showCV_chBtn")
        self.verticalLayout_6.addWidget(self.showCV_chBtn)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.saveSettingsBtn = QtWidgets.QPushButton(self.frameSettings)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/../data/Logos/diskette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveSettingsBtn.setIcon(icon)
        self.saveSettingsBtn.setObjectName("saveSettingsBtn")
        self.verticalLayout_5.addWidget(self.saveSettingsBtn)
        self.verticalLayout.addWidget(self.frameSettings)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Уровень громкости:"))
        self.volLabel.setText(_translate("Form", "100"))
        self.minVolLabel.setText(_translate("Form", "0"))
        self.maxVolLabel.setText(_translate("Form", "250"))
        self.label_7.setText(_translate("Form", "Скорость воспроизведения речи:"))
        self.switchDialCheckBox.setText(_translate("Form", "Автоматически переключать диалоги \n"
"(Запустите приложение от имени Администратора)"))
        self.groupBoxPlayerNicks.setTitle(_translate("Form", "Распозновать ник игрока в диалогах"))
        self.label_5.setText(_translate("Form", "Ник игрока (в точности как на аккаунте):"))
        self.PlayerNameLineEdit.setText(_translate("Form", "Nickname"))
        self.label_6.setText(_translate("Form", "Ник игрока для озвучки (только русские буквы):"))
        self.groupBoxTrevelerGender.setTitle(_translate("Form", "Голос для озвучки реплик Путешественника:"))
        self.maleTrevelerGb.setText(_translate("Form", "Мужской"))
        self.femaleTrevelerGb.setText(_translate("Form", "Женский"))
        self.nickQuestionBtn.setText(_translate("Form", "Зачем задавать ник?"))
        self.muteNoEventNpcCheckBox.setText(_translate("Form", "Не озвучивать частых персонажей-продавцов\n"
"(Катерина, кузнецы, Чайник)"))
        self.groupBoxProcessers.setTitle(_translate("Form", "Используемый процессор"))
        self.CPU_rBtn.setText(_translate("Form", "CPU"))
        self.GPU_rBtn.setText(_translate("Form", "GPU (Nvidia CUDA)"))
        self.label_2.setText(_translate("Form", "Требуется\n"
"сохранение\n"
"и перезапуск "))
        self.groupBoxMonitors.setTitle(_translate("Form", "Монитор с игрой (если несколько мониторов)"))
        self.showMonitorNumbers.setText(_translate("Form", "Подсказать номера мониторов"))
        self.showCV_chBtn.setText(_translate("Form", "Отображать окна технического зрения (для их закрытия \n"
" сначала снимите эту галочку, а потом закройте окна)"))
        self.saveSettingsBtn.setText(_translate("Form", "Сохранить настройки"))
