# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 200)
        MainWindow.setMinimumSize(QtCore.QSize(430, 200))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Лого.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frameMain = QtWidgets.QFrame(self.centralwidget)
        self.frameMain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMain.setObjectName("frameMain")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameMain)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout()
        self.verticalLayoutMain.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutMain.setSpacing(0)
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.frameTitle = QtWidgets.QFrame(self.frameMain)
        self.frameTitle.setMinimumSize(QtCore.QSize(0, 40))
        self.frameTitle.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frameTitle.setStyleSheet("background-color: rgb(50, 50, 60);  \n"
"color: white;")
        self.frameTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTitle.setObjectName("frameTitle")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameTitle)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayoutTitle = QtWidgets.QVBoxLayout()
        self.verticalLayoutTitle.setSpacing(0)
        self.verticalLayoutTitle.setObjectName("verticalLayoutTitle")
        self.verticalLayout_6.addLayout(self.verticalLayoutTitle)
        self.verticalLayoutMain.addWidget(self.frameTitle)
        self.frameBody = QtWidgets.QFrame(self.frameMain)
        self.frameBody.setStyleSheet("#MainWindow\n"
"{\n"
"    border-color: rgb(40, 40, 50);  \n"
"}\n"
"QWidget {  \n"
"    color: white;\n"
"    background-color: rgb(40, 40, 50);  \n"
"    \n"
"}  \n"
"QPushButton {  \n"
"    color:rgb(13, 13, 15);  \n"
"    \n"
"    background-color: rgba(255, 219, 41, 220);\n"
"    border: 1px solid rgba(255, 219, 41, 220);\n"
"    border-radius: 10px;\n"
"    height: 20;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 219, 41, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 219, 41, 200);\n"
"}\n"
"QScrollBar::vertical {  \n"
"    border: none;  \n"
"    background:  rgb(150,150,150);\n"
"    margin: 3px 0 3px 0;\n"
"    border-radius: 7px;\n"
"}  \n"
"QScrollBar::handle:vertical {  \n"
"    background: rgba(255, 219, 41, 200); \n"
"    border-radius: 8px;\n"
"}  \n"
"QScrollBar::handle:vertical:hover {  \n"
"    background: rgba(255, 180, 41, 255);\n"
"}  \n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {  \n"
"    background: none; \n"
"}  \n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {  \n"
"    background: none;\n"
"}  \n"
"QSlider::handle{\n"
"     background-color: #E1C22A;\n"
"    width: 10px; \n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle::hover{\n"
"     background-color: rgba(255, 180, 41, 255);\n"
"}")
        self.frameBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBody.setObjectName("frameBody")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frameBody)
        self.verticalLayout_10.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_10.setSpacing(18)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label = QtWidgets.QLabel(self.frameBody)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(self.frameBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color: rgb(150,150,150);  \n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    color: black;\n"
"\n"
"    }\n"
"QProgressBar::chunk {\n"
"    background-color: rgba(255, 219, 41);\n"
"    border-radius: 10px;\n"
"    \n"
"} ")
        self.progressBar.setProperty("value", 10)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_10.addWidget(self.progressBar)
        self.startStopVoicerBtn = QtWidgets.QPushButton(self.frameBody)
        self.startStopVoicerBtn.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/../data/Logos/iconPause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startStopVoicerBtn.setIcon(icon1)
        self.startStopVoicerBtn.setObjectName("startStopVoicerBtn")
        self.verticalLayout_10.addWidget(self.startStopVoicerBtn)
        self.frameSettingsBase = QtWidgets.QFrame(self.frameBody)
        self.frameSettingsBase.setEnabled(True)
        self.frameSettingsBase.setObjectName("frameSettingsBase")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameSettingsBase)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayoutSettingsBase = QtWidgets.QVBoxLayout()
        self.verticalLayoutSettingsBase.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayoutSettingsBase.setObjectName("verticalLayoutSettingsBase")
        self.verticalLayout_5.addLayout(self.verticalLayoutSettingsBase)
        self.verticalLayout_10.addWidget(self.frameSettingsBase)
        self.verticalLayoutMain.addWidget(self.frameBody)
        self.verticalLayout_2.addLayout(self.verticalLayoutMain)
        self.verticalLayout_4.addWidget(self.frameMain)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Genshin speaker"))
        self.label.setText(_translate("MainWindow", "Запуск системы озвучки"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.startStopVoicerBtn.setText(_translate("MainWindow", "Остановить озвучку"))
