# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nickAnswerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 366)
        MainWindow.setMinimumSize(QtCore.QSize(430, 200))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Лого.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frameMain = QtWidgets.QFrame(self.centralwidget)
        self.frameMain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMain.setObjectName("frameMain")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameMain)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout()
        self.verticalLayoutMain.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutMain.setSpacing(0)
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.frameTitle = QtWidgets.QFrame(self.frameMain)
        self.frameTitle.setMinimumSize(QtCore.QSize(0, 40))
        self.frameTitle.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frameTitle.setStyleSheet("background-color: rgb(50, 50, 60);  \n"
"color: white;")
        self.frameTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTitle.setObjectName("frameTitle")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameTitle)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayoutTitle = QtWidgets.QVBoxLayout()
        self.verticalLayoutTitle.setSpacing(0)
        self.verticalLayoutTitle.setObjectName("verticalLayoutTitle")
        self.verticalLayout_6.addLayout(self.verticalLayoutTitle)
        self.verticalLayoutMain.addWidget(self.frameTitle)
        self.frameBody = QtWidgets.QFrame(self.frameMain)
        self.frameBody.setStyleSheet("#MainWindow\n"
"{\n"
"    border-color: rgb(40, 40, 50);  \n"
"}\n"
"QWidget {  \n"
"    color: white;\n"
"    background-color: rgb(40, 40, 50);  \n"
"    \n"
"}  \n"
"QPushButton {  \n"
"    color:rgb(13, 13, 15);  \n"
"    \n"
"    background-color: rgba(255, 219, 41, 220);\n"
"    border: 1px solid rgba(255, 219, 41, 220);\n"
"    border-radius: 10px;\n"
"    height: 20;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 219, 41, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 219, 41, 200);\n"
"}\n"
"QScrollBar::vertical {  \n"
"    border: none;  \n"
"    background:  rgb(150,150,150);\n"
"    margin: 3px 0 3px 0;\n"
"    border-radius: 7px;\n"
"}  \n"
"QScrollBar::handle:vertical {  \n"
"    background: rgba(255, 219, 41, 200); \n"
"    border-radius: 8px;\n"
"}  \n"
"QScrollBar::handle:vertical:hover {  \n"
"    background: rgba(255, 180, 41, 255);\n"
"}  \n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {  \n"
"    background: none; \n"
"}  \n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {  \n"
"    background: none;\n"
"}  \n"
"QSlider::handle{\n"
"     background-color: #E1C22A;\n"
"    width: 10px; \n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle::hover{\n"
"     background-color: rgba(255, 180, 41, 255);\n"
"}")
        self.frameBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBody.setObjectName("frameBody")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frameBody)
        self.verticalLayout_10.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_10.setSpacing(18)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label = QtWidgets.QLabel(self.frameBody)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frameBody)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.closeBtn = QtWidgets.QPushButton(self.frameBody)
        self.closeBtn.setObjectName("closeBtn")
        self.verticalLayout_10.addWidget(self.closeBtn)
        self.verticalLayoutMain.addWidget(self.frameBody)
        self.verticalLayout_2.addLayout(self.verticalLayoutMain)
        self.verticalLayout_4.addWidget(self.frameMain)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Genshin speaker"))
        self.label.setText(_translate("MainWindow", "Зачем знать никнейм игрока?"))
        self.label_2.setText(_translate("MainWindow", "\t\tПрограмме можно не задавать ник. Программа распознает в диалогах русский текст. В диалогах встречается ник игрока. Если никнэйм не на русском (например, на английском), то программа не сможет его правильно прочитать. Одновременное распознавание на нескольких языках проблематично, так как это: первое - ухудшает производительность, второе - есть символы, которые пишутся практически одинаково на обоих языках, что вносит путаницу.\n"
"\t\tА зная имя игрока, программа сможет определить, что вот это непонятное слово является ником игрока, и вы сами говорите программе как произносить его на русском. \n"
"\t\tВообще вариант произношения никнейма можно задать любым, программе это не важно, она его просто будет озвучивать вместо непонятного слова, которым считается ваш ник.\n"
""))
        self.closeBtn.setText(_translate("MainWindow", "Закрыть"))
