# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'titleBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_titleBar(QtWidgets.QWidget):
    def setupUi(self, titleBar):
        titleBar.setObjectName("titleBar")
        titleBar.resize(410, 42)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(titleBar.sizePolicy().hasHeightForWidth())
        titleBar.setSizePolicy(sizePolicy)
        titleBar.setMinimumSize(QtCore.QSize(0, 40))
        titleBar.setMaximumSize(QtCore.QSize(16777215, 42))
        titleBar.setStyleSheet("background-color: rgb(50, 50, 60);  \n"
"color: white;\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(titleBar)
        self.horizontalLayout.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon = QtWidgets.QLabel(titleBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon.sizePolicy().hasHeightForWidth())
        self.icon.setSizePolicy(sizePolicy)
        self.icon.setMinimumSize(QtCore.QSize(35, 35))
        self.icon.setMaximumSize(QtCore.QSize(35, 35))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/../data/Logos/Logo64x64.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.horizontalLayout.addWidget(self.icon)
        self.title = QtWidgets.QLabel(titleBar)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        self.buttonsFrame = QtWidgets.QFrame(titleBar)
        self.buttonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonsFrame.setObjectName("buttonsFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttonsFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_min = QtWidgets.QPushButton(self.buttonsFrame)
        self.btn_min.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_min.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_min.setStyleSheet("QPushButton {  \n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 20);\n"
"}")
        self.btn_min.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/../data/Logos/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_min.setIcon(icon)
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout_2.addWidget(self.btn_min)
        self.btn_close = QtWidgets.QPushButton(self.buttonsFrame)
        self.btn_close.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_close.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_close.setStyleSheet("QPushButton {  \n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 20);\n"
"}")
        self.btn_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.dirname(__file__) + "/../data/Logos/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon1)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.buttonsFrame, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(titleBar)
        QtCore.QMetaObject.connectSlotsByName(titleBar)

    def retranslateUi(self, titleBar):
        _translate = QtCore.QCoreApplication.translate
        titleBar.setWindowTitle(_translate("titleBar", "Form"))
        self.title.setText(_translate("titleBar", "Genshin Speaker"))
